version: '3.6'

services:
  rabbitmq:
    build: rabbitmq
    image: my-rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    restart: on-failure
    ports:
      - 15672:15672
      - 5672:5672
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/

  redis:
    image: bitnami/redis:5.0
    hostname: redis
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=123456

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: on-failure
    env_file:
      - redis.env
    ports:
      - "16379:8081"
    depends_on:
      - redis


  oracle:
    build: oracle
    image: my-oracle
    container_name: oracle
    hostname: oracle
    restart: on-failure
    ports: 
      - 1521:1521
    environment: 
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true 
      - ORACLE_ENABLE_XDB=false

