CREATE USER ASSEMBLY_OWNER IDENTIFIED BY 123456 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;

CREATE USER ASSEMBLY_RUN IDENTIFIED BY 123456 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE, DBA TO ASSEMBLY_OWNER;

GRANT CONNECT TO ASSEMBLY_RUN;
