INSERT INTO ASSEMBLY_OWNER.AGENDA(ID,DESCRIPTION) values (1,'test agenda');
INSERT INTO ASSEMBLY_OWNER.AGENDA(ID,DESCRIPTION) values (2,'test agenda2');
INSERT INTO ASSEMBLY_OWNER.VOTING_SESSION(ID,AGENDA_ID,START_VOTING_SESSION,FINISH_VOTING_SESSION,OPENED) values (1,1,to_date('17-01-2030', 'dd-mm-yyyy'),to_date('17-01-2030', 'dd-mm-yyyy'),0);
INSERT INTO ASSEMBLY_OWNER.VOTING_SESSION(ID,AGENDA_ID,START_VOTING_SESSION,FINISH_VOTING_SESSION,OPENED) values (2,2,to_date('17-01-2030', 'dd-mm-yyyy'),to_date('17-01-2030', 'dd-mm-yyyy'),1);
INSERT INTO ASSEMBLY_OWNER.VOTE(ID,VOTE_SESSION_ID,DOCUMENT,DECISION) values (1,1,'83714006087','YES');
INSERT INTO ASSEMBLY_OWNER.VOTE(ID,VOTE_SESSION_ID,DOCUMENT,DECISION) values (2,1,'83714006087','NO');
INSERT INTO ASSEMBLY_OWNER.VOTE(ID,VOTE_SESSION_ID,DOCUMENT,DECISION) values (3,2,'83714006087','YES');
INSERT INTO ASSEMBLY_OWNER.VOTE(ID,VOTE_SESSION_ID,DOCUMENT,DECISION) values (4,2,'83714006087','NO');
