CREATE Schema IF NOT EXISTS ASSEMBLY_OWNER;
CREATE TABLE IF NOT EXISTS ASSEMBLY_OWNER.AGENDA(ID NUMBER(10) NOT NULL, DESCRIPTION VARCHAR2(300) NOT NULL);
CREATE TABLE IF NOT EXISTS ASSEMBLY_OWNER.VOTING_SESSION(ID NUMBER(10) NOT NULL, AGENDA_ID INTEGER NOT NULL,FINISH_VOTING_SESSION TIMESTAMP NOT NULL,OPENED NUMBER(1) NOT NULL);
CREATE TABLE IF NOT EXISTS ASSEMBLY_OWNER.VOTE(ID NUMBER(10) NOT NULL, VOTE_SESSION_ID INTEGER NOT NULL,DOCUMENT VARCHAR2(11) NOT NULL,DECISION NUMBER(1) NOT NULL);
